---
functional:
  - Пользователь должен иметь возможность просматривать каталог товаров.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность добавлять товары в корзину.
  - Пользователь должен иметь возможность просматривать содержимое корзины.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Пользователь должен иметь возможность оформлять заказ с переходом на страницу оплаты.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - На странице товара и в каталоге должно быть отображение названия, рейтинга, цены со скидкой и без нее.

non-functional:
  - Сайт должен быть адаптивным и удобным на мобильных устройствах.
  - Сайт должен быть SPA-приложением, которое не перезагружает страницу.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть оптимизирован для скорости работы.
  - Сайт должен быть совместим с последними версиями браузеров.
  - Сайт должен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.

implicit:
  - Корзина должна храниться в сессии браузера.
  - Необходимо реализовать постраничный вывод товаров.
  - Переход между страницами каталога и корзины должен быть без перезагрузки.
  - Оформление заказа должно включать переход на страницу оплаты.
  - Сайт должен быть доступен для пользователей с различными типами устройств (компьютеры, планшеты, мобильные телефоны).
  - Возможности поиска и фильтрации должны работать быстро и эффективно.
